declare const ghostClassName: string;
declare const outlineClassName: string;
declare const bannerClassName: string;
declare const tabsClassNames: Readonly<Record<"list" | "tab", string>>;
declare const linkClassName: string;
declare const sheetClassNames: Readonly<Record<"body" | "footer" | "handle" | "root" | "title", string>>;
declare const pressableClassName: string;
declare const comboboxClassNames: Readonly<Record<"label" | "list" | "root", string>>;
declare const switchClassNames: Readonly<Record<"icon" | "root" | "thumb", string>>;
declare const avatarClassName: string;
declare const fabClassName: string;
declare const alertClassNames: Readonly<Record<"icon" | "root", string>>;
declare const drawerClassNames: Readonly<Record<"body" | "footer" | "root" | "title", string>>;
declare const footedDialogClassNames: Readonly<Record<"body" | "footer" | "root" | "title", string>>;
export { alertClassNames, bannerClassName, avatarClassName, comboboxClassNames, drawerClassNames, fabClassName, footedDialogClassNames, ghostClassName, linkClassName, outlineClassName, pressableClassName, sheetClassNames, switchClassNames, tabsClassNames, };
