import type { NativeStyle, SlotStyles } from "native-recipe-library";
declare const toolbarStyles: SlotStyles<"divider" | "icon" | "label" | "root">;
declare const tileStyle: NativeStyle;
declare const sheetStyles: SlotStyles<"handle" | "root" | "title">;
declare const pillTagStyles: SlotStyles<"close" | "label" | "root">;
declare const noticeStyle: NativeStyle;
declare const tabsStyles: SlotStyles<"list" | "tab">;
declare const spacerStyle: NativeStyle;
declare const avatarStyle: NativeStyle;
declare const fabStyle: NativeStyle;
declare const alertStyles: SlotStyles<"icon" | "root">;
declare const footedFieldStyles: SlotStyles<"footer" | "label" | "root">;
declare const footedButtonStyles: SlotStyles<"footer" | "label" | "root">;
export { alertStyles, avatarStyle, fabStyle, footedButtonStyles, footedFieldStyles, noticeStyle, pillTagStyles, sheetStyles, spacerStyle, tabsStyles, tileStyle, toolbarStyles, };
